### ISSUE TITLE
Segmentation fault on ZAP 2.13.0

### ISSUE THREAD

**Issue by arkenoi** [hahwul/mzap#16]
Since it happens both with snap and local version of mzap and I tried both Kali bundled ZAP and manual install, I think it is ZAP API/compatibility issue.

Sep  1 18:43:19.082 [INFO] [active-scan] start
Sep  1 18:43:19.083 [INFO] [active-scan] [http://localhost:8090] [REDACTED] added
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x676a31]

goroutine 1 [running]:
github.com/hahwul/mzap/pkg/zap.Run({0x7ffe7c85b107, 0x11}, {0x81dec2, 0x15}, {0x81f636, 0x18}, {{0x0, 0x0}, {0x0, 0x0}})
	/Users/ichei/Projects/release/mzap/pkg/zap/zap.go:96 +0x991
github.com/hahwul/mzap/pkg/zap.ActiveScan(...)
	/Users/ichei/Projects/release/mzap/pkg/zap/interface.go:19
github.com/hahwul/mzap/cmd.glob..func2(0xb33aa0, {0x817711, 0x2, 0x2})
	/Users/ichei/Projects/release/mzap/cmd/ascan.go:15 +0x7a
github.com/spf13/cobra.(*Command).execute(0xb33aa0, {0xc0000664c0, 0x2, 0x2})
	/Users/ichei/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xb33d20)
	/Users/ichei/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ichei/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/hahwul/mzap/cmd.Execute()
	/Users/ichei/Projects/release/mzap/cmd/root.go:25 +0x25
main.main()
	/Users/ichei/Projects/release/mzap/main.go:6 +0x17

**Comment by hahwul** [comment]
Hi @arkenoi 
Thank you for the report! I've tested a few things, and it seems that there might be issues with ZAP when using "Secure Only" or an API Key. I'll work on fixing this as soon as possible. I really appreciate your help!

**Comment by hahwul** [comment]
Hi @arkenoi 
It was fixed in version [v1.3.1](https://github.com/hahwul/mzap/releases/tag/v1.3.1). If the same issue happens again, please reopen the issue!

![](https://github.com/hahwul/mzap/assets/13212227/95f251fd-4427-41b3-bc88-fc39d354c381)
*left: v1.3.1 / right: v1.3.0*
